name: GitHub-Profile-3D-Contrib-simplify
description: Generate profile 3D Contributions simplified
author: jung217

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
